### ISSUE TITLE
TODO for V1.1

### ISSUE THREAD

**Issue by AndrewRathbun** [Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts#147]
- [x] Change author subheadings from `##` to `###` - https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/commit/34da71a3f64b0ab3bd13f4350e881466fd543b8c
- [x] remove `:` from Chapter 4's subheadings - https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/commit/c832a4f6b891dd5260abe173de9ea33f533d3534
- [x] add status of 2022 Forensic 4:cast Awards - https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/commit/e0c85c6dec069654ecfb388fb94385358bbd280c
- [x] Add mention of https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/graphs/contributors so smaller contributions can be recognized - EDIT: this is done - https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/commit/476a0cb09132134363970071a3add54aa320476c
- [x] Added recent contributors to Contributors section - https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/commit/3d29e14540136c7bdf9d159a1bd55b924414928e and https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/commit/d4470948bbec2c4f1e793e6a85ab7e193edfc671
- [x] At least one new chapter - https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/blob/main/manuscript/chapter11.txt
- [ ] Add Disclaimer - https://github.com/Digital-Forensics-Discord-Server/TheHitchhikersGuidetoDFIRExperiencesFromBeginnersandExperts/issues/159
- [ ] Add link to 2022 Forensic 4:cast Awards when it goes live - TBD, may have to wait for v1.2

This list will be added to as time goes on!

**Comment by AndrewRathbun** [comment]
I am going to use GitHub releases instead of linking to this Issue in the book
